services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: test_db
      #MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: test_user
      MYSQL_PASSWORD: pass
    volumes:
      - ./backend/data:/docker-entrypoint-initdb.d # create table when container starts
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      timeout: 2s
      retries: 20
  fastapi:
    image: santa-server:0.0.1
    build:
      context: ./backend
    ports:
      - 8000:8000
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      CONNECTION_URL: "mysql://test_user:pass@mysql:3306/test_db" # override CONNECTION_URL in env_file
    env_file:
      - .env
